### ISSUE TITLE
Typesctipt does not comile

### ISSUE THREAD

**Issue by SamJust** [nitreojs/puregram#71]
## The bug
The typescript does not compile when I have used the Puregram package for the TelegramBot.

## Steps to reproduce
1. Create a TS server with Puregram
2. Try to build it.

## Expected behavior
Typescript builds without errors.

## Environment
| package         | version |
| :-----------:   | :-----: |
| `puregram`      | `2.9.8` |
| `node`          | `18.12.1` |
| `TypeScript`    | `4.7.4` |
| `yarn` | `1.22.19` |

## Additional context
` node_modules/puregram/lib/common/structures/composer.d.ts:3:22 - error TS2417: Class static side 'typeof import("/path/to/my/app/node_modules/puregram/lib/common/structures/composer").Composer' incorrectly extends base class static side 'typeof import("/path/to/my/app/node_modules/middleware-io/lib/composer").Composer'.
  The types of 'builder().middlewares' are incompatible between these types.
    Type 'import("/path/to/my/app/node_modules/middleware-io/lib/types").Middleware<import("/path/to/my/app/node_modules/puregram/lib/contexts/context").Context>[]' is not assignable to type 'import("/path/to/my/app/node_modules/middleware-io/lib/types").Middleware<Context>[]'.
      Type 'import("/path/to/my/app/node_modules/middleware-io/lib/types").Middleware<import("/path/to/my/app/node_modules/puregram/lib/contexts/context").Context>' is not assignable to type 'import("/path/to/my/app/node_modules/middleware-io/lib/types").Middleware<Context>'.
        Type 'Context' is not assignable to type 'import("/path/to/my/app/node_modules/puregram/lib/contexts/context").Context'.
          Type 'UnknownObject' is missing the following properties from type 'Context': telegram, updateType, is, [Symbol.toStringTag]

3 export declare class Composer<T extends Context> extends MiddlewareComposer<T> {
                       ~~~~~~~~

node_modules/puregram/lib/common/structures/composer.d.ts:3:77 - error TS2344: Type 'T' does not satisfy the constraint 'UnknownObject'.
  Type 'Context' is not assignable to type 'UnknownObject'.
    Index signature for type 'string' is missing in type 'Context'.

3 export declare class Composer<T extends Context> extends MiddlewareComposer<T> {
                                                                              ~

node_modules/puregram/lib/contexts/chat-join-request.d.ts:17:11 - error TS2320: Interface 'ChatJoinRequestContext' cannot simultaneously extend types 'ChatJoinRequest' and 'TargetMixin'.
  Named property 'from' of types 'ChatJoinRequest' and 'TargetMixin' are not identical.

17 interface ChatJoinRequestContext extends Constructor<ChatJoinRequestContext>, ChatJoinRequest, TargetMixin, SendMixin, CloneMixin<ChatJoinRequestContext, ChatJoinRequestContextOptions> {
             ~~~~~~~~~~~~~~~~~~~~~~

node_modules/puregram/lib/contexts/chat-member.d.ts:20:11 - error TS2320: Interface 'ChatMemberContext' cannot simultaneously extend types 'ChatMemberUpdated' and 'TargetMixin'.
  Named property 'from' of types 'ChatMemberUpdated' and 'TargetMixin' are not identical.

20 interface ChatMemberContext extends Constructor<ChatMemberContext>, ChatMemberUpdated, TargetMixin, SendMixin, CloneMixin<ChatMemberContext, ChatMemberContextOptions> {
             ~~~~~~~~~~~~~~~~~

node_modules/puregram/lib/contexts/chosen-inline-result.d.ts:25:11 - error TS2320: Interface 'ChosenInlineResultContext' cannot simultaneously extend types 'ChosenInlineResult' and 'SendMixin'.
  Named property 'senderId' of types 'ChosenInlineResult' and 'SendMixin' are not identical.

25 interface ChosenInlineResultContext extends Constructor<ChosenInlineResultContext>, ChosenInlineResult, SendMixin, CloneMixin<ChosenInlineResultContext, ChosenInlineResultContextOptions> {
             ~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/puregram/lib/contexts/poll-answer.d.ts:17:11 - error TS2320: Interface 'PollAnswerContext' cannot simultaneously extend types 'PollAnswer' and 'SendMixin'.
  Named property 'senderId' of types 'PollAnswer' and 'SendMixin' are not identical.

17 interface PollAnswerContext extends Constructor<PollAnswerContext>, PollAnswer, SendMixin, CloneMixin<PollAnswerContext, PollAnswerContextOptions> {
             ~~~~~~~~~~~~~~~~~

node_modules/puregram/lib/contexts/pre-checkout-query.d.ts:24:11 - error TS2320: Interface 'PreCheckoutQueryContext' cannot simultaneously extend types 'PreCheckoutQuery' and 'SendMixin'.
  Named property 'senderId' of types 'PreCheckoutQuery' and 'SendMixin' are not identical.

24 interface PreCheckoutQueryContext extends Constructor<PreCheckoutQueryContext>, PreCheckoutQuery, SendMixin, CloneMixin<PreCheckoutQueryContext, PreCheckoutQueryContextOptions> {
             ~~~~~~~~~~~~~~~~~~~~~~~

node_modules/puregram/lib/contexts/shipping-query.d.ts:17:11 - error TS2320: Interface 'ShippingQueryContext' cannot simultaneously extend types 'ShippingQuery' and 'SendMixin'.
  Named property 'senderId' of types 'ShippingQuery' and 'SendMixin' are not identical.

17 interface ShippingQueryContext extends Constructor<ShippingQueryContext>, ShippingQuery, SendMixin, CloneMixin<ShippingQueryContext, ShippingQueryContextOptions> { `

**Comment by nitreojs** [comment]
first of all, are you sure you **need** to compile the `puregram` by hand? can't you just use the built version (I mean the version published on **npm**) and not poke around the source code?
secondly, what OS specifically do you have? if that's Windows, do you have WSL installed? if so, do you work on it on a daily basis (including compiling `puregram`) and what subsystem is installed here? 
thirdly, have you done any changes to the code so it became "uncompilable"? _is that even a word?_

**Comment by nitreojs** [comment]
try updating your typescript version. I tried to compile `puregram` and it compiled on the first try: 
![image](https://user-images.githubusercontent.com/40319427/213348992-011ac8e8-55b8-40d4-ac85-c0f362694e18.png)

**Comment by SamJust** [comment]
@nitreojs 
I did not try to compile the project itself. I only have it as dependency. Here is an example repo that seems to lead to the same result as my own. https://github.com/SamJust/puregram-issue-71
I'm running this on MacOS 10.15.7.

**Comment by nitreojs** [comment]
> @nitreojs I did not try to compile the project itself. I only have it as dependency. Here is an example repo that seems to lead to the same result as my own. https://github.com/SamJust/puregram-issue-71 I'm running this on MacOS 10.15.7.

🤔 throws error on my system, too. seems like it's a problem with mixins (if we ignore the first Composer error), for example `from @ TargetMixin` is `User | undefined` while `from @ ChatJoinRequestContext[extends ChatJoinRequest]` is `User`. this might be fixed very easily by just suppressing these errors - everything will get resolved correctly since the upper level is the *Context one

the same applies to the `Composer` error - seems like @negezor used `UnknownObject` as a generic type (which resolves to `Record<string, unknown>`) but, as we all know, `Context` is a class and `Record<...>` is an object, thus it fails to execute `Context extends UnknownObject` ... and again, the easiest and probably the best fix for this is the **error suppression**. I may try to find and exclusive fix for these ones but that won't happen in the near future - too busy :P

**Comment by nitreojs** [comment]
if you want, I may release a special version with those fixes - I mean, it will be just a bunch of error suppressions which will be added to my imaginary TODO list for later :P

**Comment by SamJust** [comment]
@nitreojs Sorry for a little bit of a delay in replies. I would very much appreciate the version where you'd suppress the errors.

**Comment by SamJust** [comment]
@nitreojs ping

**Comment by nitreojs** [comment]
@SamJust hey, just got time to inspect the issue, and I have some news for you
first of all, the issue actually does not exist when compiling using sources--only when using .d.ts files (which are generated after the compilation). this happens because comments are being removed after the compilation process, and such compiler tags as `@ts-expect-error` etc. are also comments.
what am I trying to say is that after the compilation all comments are gone, and so are compiler tags. I will inspect what can I do about this right now

UPD. actually, comments do not remove entirely - they're just being moved to the .js filed instead of .d.ts file, which causes some issues... yeah, that definitely requires some thinking

**Comment by nitreojs** [comment]
seems like this issue is stale as no answer was provided.
there was an issue that looks just like yours (https://github.com/nitreojs/puregram/issues/85), and they fixed it with providing `"skipLibCheck": true` to the `tsconfig.json`

i will close this issue for now. if this does not fix your problem, feel free to reopen the issue! i will be glad to talk about it
